variables:
  - name: author
    value: 'AzureToujours'
  - name: published
    value: 'last week'

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Module -Name 'powershell-yaml' -Force -Scope CurrentUser

- powershell: |
    $yamlFilePath = "$(System.DefaultWorkingDirectory)/config/test.yaml"
    .\powershell\replaceYaml.ps1 -yamlFilePath $yamlFilePath -published "$(published)" -author "$(author)"
  displayName: 'Update YAML Configuration'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
